# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-27 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('bo', 'བོད་ཡིག')], default='bo', max_length=10),
        ),
    ]
