# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_locale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('bo', 'Tibetan')], default='bo', max_length=10),
        ),
    ]
