# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-12 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sso_username',
            field=models.CharField(blank=True, help_text='The extenal username if using sso.', max_length=200, null=True, verbose_name='sso username'),
        ),
    ]
