# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 06:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('length', models.IntegerField()),
                ('content', models.CharField(blank=True, max_length=4000, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_variant', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppliedUserAnnotations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='texts.Annotation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultWitnessAnnotations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='texts.Annotation')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(default=1)),
                ('content', models.TextField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='texts.Source')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='texts.Text')),
            ],
        ),
        migrations.AddField(
            model_name='defaultwitnessannotations',
            name='witness',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='texts.Witness'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='creator_witness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_witness', to='texts.Witness'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='witness',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='texts.Witness'),
        ),
    ]
