# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 07:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applieduserannotations',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annotation',
            name='creator_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annotation',
            name='creator_witness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_witness', to='texts.Witness'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='witness',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='texts.Witness'),
        ),
    ]
