# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0002_auto_20170219_0704'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppliedUserAnnotations',
            new_name='AppliedUserAnnotation',
        ),
    ]
