# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 10:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0003_auto_20180627_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='witness',
            name='properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
