# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0003_auto_20170321_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='is_variant',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='note',
        ),
        migrations.AddField(
            model_name='annotation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotation',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='type',
            field=models.CharField(choices=[('V', 'Variant'), ('N', 'Note')], default='V', max_length=1),
        ),
    ]
