# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 01:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0004_auto_20170427_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='texts.Annotation'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='creator_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='creator_witness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_witness', to='texts.Witness'),
        ),
    ]
