# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0005_auto_20170428_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
