# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-06 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0006_text_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='texts.Author'),
        ),
    ]
