# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-03 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0006_annotation_unique_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='is_default_base_text',
            new_name='is_base_edition',
        ),
        migrations.AddField(
            model_name='source',
            name='is_working_edition',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='type',
            field=models.CharField(choices=[('V', 'Variant'), ('N', 'Note'), ('P', 'Page Break')], default='V', max_length=1),
        ),
    ]
