# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-15 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0009_auto_20201014_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topic_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
