# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-19 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0010_auto_20201015_1012'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['witness_id', 'start', 'length'], name='texts_annot_witness_944e73_idx'),
        ),
    ]
