# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-19 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0011_auto_20201019_1000'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='annotation',
            name='texts_annot_witness_944e73_idx',
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['witness_id', 'start', 'length', 'type'], name='texts_annot_witness_53dc2d_idx'),
        ),
    ]
