# Generated by Django 3.2.12 on 2022-08-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0015_featuredtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredtext',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='featuredtext',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
