# Generated by Django 3.2.12 on 2022-08-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0016_auto_20220809_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredtext',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
