# Generated by Django 3.2.12 on 2022-08-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0017_featuredtext_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredtext',
            name='author',
            field=models.CharField(blank=True, choices=[{'dawa', 'one'}, {'two', 'kalden'}], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='featuredtext',
            name='category',
            field=models.CharField(blank=True, choices=[{'root', 'one'}, {'commentary', 'two'}], max_length=100, null=True),
        ),
    ]
