# Generated by Django 3.2.12 on 2022-08-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0018_auto_20220810_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredtext',
            name='author',
            field=models.CharField(blank=True, choices=[{'dawa', '1'}, {'2', 'kalden'}], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='featuredtext',
            name='category',
            field=models.CharField(blank=True, choices=[{'root', '1'}, {'commentary', '2'}], max_length=100, null=True),
        ),
    ]
