# Generated by Django 3.2.12 on 2022-08-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0019_auto_20220810_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredtext',
            name='author',
            field=models.CharField(blank=True, choices=[('dawa', 'dawa'), ('kalden', 'kalden')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='featuredtext',
            name='category',
            field=models.CharField(blank=True, choices=[('root', 'root'), ('commentary', 'commentary')], max_length=100, null=True),
        ),
    ]
