# Generated by Django 3.2.12 on 2022-08-16 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0020_auto_20220810_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredtext',
            name='author',
        ),
        migrations.RemoveField(
            model_name='featuredtext',
            name='category',
        ),
        migrations.RemoveField(
            model_name='featuredtext',
            name='length',
        ),
    ]
