# Generated by Django 3.2.12 on 2022-06-18 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('texts', '0014_auto_20220618_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagegroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdrc_imagegroup_id', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='VideoAlignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alignment', models.JSONField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alignments_videoalignment_source', to='texts.text')),
                ('target_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_video', to='alignments.video')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextAlignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alignment', models.JSONField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alignments_textalignment_source', to='texts.text')),
                ('target_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_text', to='texts.text')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageAlignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alignment', models.JSONField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alignments_imagealignment_source', to='texts.text')),
                ('target_imagegroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_imagegroup', to='alignments.imagegroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
