# Generated by Django 3.2.12 on 2022-06-18 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0014_auto_20220618_0700'),
        ('alignments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagealignment',
            name='target_imagegroup',
        ),
        migrations.RemoveField(
            model_name='textalignment',
            name='target_text',
        ),
        migrations.RemoveField(
            model_name='videoalignment',
            name='target_video',
        ),
        migrations.AddField(
            model_name='imagealignment',
            name='target',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='alignment_image', to='alignments.imagegroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textalignment',
            name='target',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='alignment_text', to='texts.text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videoalignment',
            name='target',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='alignment_video', to='alignments.video'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagealignment',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alignments_imagealignment_related', to='texts.text'),
        ),
        migrations.AlterField(
            model_name='textalignment',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alignments_textalignment_related', to='texts.text'),
        ),
        migrations.AlterField(
            model_name='videoalignment',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alignments_videoalignment_related', to='texts.text'),
        ),
    ]
