# Generated by Django 3.2.12 on 2022-06-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignments', '0003_auto_20220619_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagealignment',
            name='type',
            field=models.CharField(blank=True, choices=[('T', 'Text'), ('I', 'Image'), ('V', 'Video')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='textalignment',
            name='type',
            field=models.CharField(blank=True, choices=[('T', 'Text'), ('I', 'Image'), ('V', 'Video')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='videoalignment',
            name='type',
            field=models.CharField(blank=True, choices=[('T', 'Text'), ('I', 'Image'), ('V', 'Video')], max_length=1, null=True),
        ),
    ]
