# Generated by Django 3.2.12 on 2022-06-29 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0014_auto_20220618_0700'),
        ('alignments', '0004_auto_20220623_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagealignment',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alignments_imagealignment_related', to='texts.witness'),
        ),
        migrations.AlterField(
            model_name='textalignment',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alignments_textalignment_related', to='texts.witness'),
        ),
        migrations.AlterField(
            model_name='textalignment',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alignment_text', to='texts.witness'),
        ),
        migrations.AlterField(
            model_name='videoalignment',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alignments_videoalignment_related', to='texts.witness'),
        ),
    ]
